# code: language=ansible

---
- hosts: ["dev", "servers"]
  become: false
  gather_facts: true
  any_errors_fatal: true
  collections:
    - community.general
  vars:
    git_user:
      - key: user.name
        value: pythoninthegrass
      - key: user.email
        value: 4097471+pythoninthegrass@users.noreply.github.com
  environment:
    EDITOR: vim
  roles:
    - pre-tasks
  pre_tasks:
    - name: Cross-platform dependencies
      ansible.builtin.package:
        name:
        - acl
        - git
        state: present
      become: true
      tags: pre

    - name: Register ~/.gitconfig user.name and user.email
      ansible.builtin.shell: |
        git config --global user.name "{{ git_user.0.value }}"
        git config --global user.email "{{ git_user.1.value }}"
      become: false
      tags: pre
  tasks:
    - name: Add a setting to ~/.gitconfig
      community.general.git_config:
        name: alias.amend
        scope: global
        value: commit --amend --no-edit
      become: false

    - name: Add a setting to ~/.gitconfig
      community.general.git_config:
        name: push.autoSetupRemote
        scope: global
        value: true
      become: false

    - name: Setup directory for git repos
      ansible.builtin.file:
        path: "{{ home_dir }}/git"
        state: directory
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        recurse: false
      become: false
