# code: language=ansible

---
- hosts: node
  become: false
  gather_facts: true
  any_errors_fatal: true
  # vars:
  environment:
    EDITOR: vim
    PATH: |
      "{{ ansible_env.HOME }}/.asdf/bin:{{ ansible_env.HOME }}/.asdf/shims:{{ ansible_env.PATH }}"
  roles:
    - pre-tasks
  tasks:
    - name: Add longhorn repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
        state: present
      tags: longhorn,qa

    - name: Install longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        chart_version: 1.6.0
        release_namespace: longhorn-system
        create_namespace: true
      tags: longhorn,qa

    - name: Read longhorn_user and longhorn_pass from ansible-vault
      ansible.builtin.include_vars:
        file: "{{ tld }}/vault.yml"
        name: vault
      tags: longhorn,qa

    - name: Create a secret from the basic auth credentials
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: basic-auth
            namespace: longhorn-system
          type: Opaque
          data:
            username: "{{ vault['longhorn_user'] | b64encode }}"
            password: "{{ vault['longhorn_pass'] | b64encode }}"
      tags: longhorn,qa

    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io
        state: present
      become: true
      tags: cert-manager

    - name: Install cert-manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        chart_version: 1.14.5
        release_namespace: cert-manager
        create_namespace: true
        set_values:
          installCRDs: true
      become: true
      tags: cert-manager
